### ISSUE TITLE
Continuous multiple lines of block quotes

### ISSUE THREAD

**Issue by ray-1337** [ItzDerock/discord-markdown-parser#7]
I think it will be better if we can cut the block quotes after two lines (or more) of break lines

# Raw
![image](https://github.com/ItzDerock/discord-markdown-parser/assets/33544674/06446c72-0252-4128-8d5e-602c1c281165)

# Preview
![image](https://github.com/ItzDerock/discord-markdown-parser/assets/33544674/335fc5f3-6723-4eec-9699-c75ab11236f3)

**Comment by ItzDerock** [comment]
this is intentional, in discord if you send 

```md
>>> line 1



3 newlines
```


it renders as

> line 1
> 
> 
> 
> 3 newlines


![image](https://github.com/ItzDerock/discord-markdown-parser/assets/14848722/1b56b70d-304b-4962-94da-61cb13175ad5)
